name: Docker Pipeline

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: DockerFiles/Ubuntu/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ubuntutest:latest