name: Docker Pipeline

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - 
        name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/ubuntutest
          flavor: latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
      -
        name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: DockerFiles/Ubuntu/Dockerfile
          push: true
          #repository: fellware/ubuntu
          tags: ${{ steps.meta.outputs.tags }} #${{ secrets.DOCKERHUB_USERNAME }}/ubuntutest:latest2, ${{ secrets.DOCKERHUB_USERNAME }}/ubuntutest:${{ github.run_number }}
          labels: ${{ steps.meta.outputs.labels }}